name: Update README with Activity

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          MAX_LINES: 5
          TARGET_FILE: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
